language: C
before_script:
 - powershell -command "New-Item -Path c:\temp -ItemType Directory"
 - powershell -command "Invoke-WebRequest -Uri https://www.cygwin.com/setup-x86_64.exe -OutFile c:\temp\setup-x86_64.exe"
 - dir c:\\temp
 - c:\\temp\\setup-x86_64.exe --quiet-mode --disable-buggy-antivirus --upgrade-also --wait --arch="x86" --root="c:\\cygwin" --only-site --site="http://cygwin.mirror.constant.com/" --packages="bash,p7zip,libssl-devel,git,gcc-core,make,diff,autoconf,automake,m4,libtool,libncurses-devel,libreadline-devel" --verbose --no-admin

matrix:
  include:
    - os: windows
      script:
        - c:\\cygwin\\bin\\bash.exe --login -c "pwd"
        - c:\\cygwin\\bin\\bash.exe --login -c "git clone --depth=50 --branch=master https://github.com/dqac-adlink/ipmitool.git dqac-adlink/ipmitool"
        - c:\\cygwin\\bin\\bash.exe --login -c "ls -al"
        - c:\\cygwin\\bin\\bash.exe --login -c "cd build && ls -al"
        - c:\\cygwin\\bin\\bash.exe --login -c "cd build/dqac-adlink && ls -al"
        - c:\\cygwin\\bin\\bash.exe --login -c "cd build/dqac-adlink/ipmitool && ls -al"
        - c:\\cygwin\\bin\\bash.exe --login -c "cd build/dqac-adlink/ipmitool && ./bootstrap 2>&1"
        # - c:\\cygwin\\bin\\bash.exe --login -c "cd build/dqac-adlink/ipmitool && ./bootstrap"
        # - c:\\cygwin\\bin\\bash.exe --login -c "cd build/dqac-adlink/ipmitool && ./configure IANADIR="./" IANAUSERDIR="./" DEFAULT_INTF="lanplus" --enable-intf-lan --enable-intf-lanplus --disable-intf-bmc --disable-intf-free --disable-intf-open --disable-intf-imb --disable-intf-usb --enable-intf-serial --enable-ipmishell"
        # - c:\\cygwin\\bin\\bash.exe --login -c "cd build/dqac-adlink/ipmitool && LANG=C make"
