language: C
before_script:
 - ./bootstrap
addons:
  apt:
    update: true
    packages:
      - libssl-dev
  homebrew:
    packages:
      - openssl

matrix:
  include:
    - os: windows
      addons:
        apt:
          packages:
            - libsystemd-dev
      script:
        - ./configure --enable-intf-dummy --enable-intf-dbus
        - make
        - sudo make install
